import React from 'react';
import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import { ThemeProvider } from 'next-themes';
import classNames from 'classnames';

const inter = Quicksand({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Richárd Nagy - Javascript Engineer',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={classNames(
          inter.className,
          'bg-none bg-white dark:bg-black'
        )}
      >
        <ThemeProvider attribute="class">
          <Header />
          <main className="py-6">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
