import classNames from 'classnames';
import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import { Quicksand } from 'next/font/google';
import React from 'react';
import './globals.css';
import Header from './_components/Header/Header';
import Container from './_components/Container/Container';
import Footer from './_components/Footer/Footer';

const inter = Quicksand({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Richárd Nagy - Javascript Engineer',
  description: 'Generated by create next app',
};

const Layout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="en" suppressHydrationWarning>
    <body
      className={classNames(
        inter.className,
        'bg-none bg-white dark:bg-black min-h-screen flex flex-col'
      )}
    >
      <ThemeProvider attribute="class">
        <Header />
        <main className="py-6 flex-grow">
          <Container>{children}</Container>
        </main>
        <Footer />
      </ThemeProvider>
    </body>
  </html>
);

export default Layout;
