name: Build application
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: yarn typecheck

  build-app:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build the Next.js app
        run: yarn build
        env:
          G_USER: ${{ secrets.G_USER }}
          G_TOKEN: ${{ secrets.G_TOKEN }}

  update-version:
    name: Update version
    runs-on: ubuntu-latest
    needs: [build-app]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "RichardRNStudio"
          git config --global user.email "info@rnstudio.hu"

      - name: Update version
        run: |
          npm version patch -m "Bump version to %s"
          git push --force --follow-tags
        env:
          NODE_AUTH_TOKEN: ${{secrets.ACTIONS_PAT}}