name: Check Pull Request
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: npx tsc

  build-app:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build the Next.js app
        run: yarn build
        env:
          G_USER: ${{ secrets.G_USER }}
          G_TOKEN: ${{ secrets.G_TOKEN }}
